-- Database: GLOBALCIG Metadata version: 2 Exported: Mar 9, 2020
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_5787_CLASS_TYPE" USING 'GCG_5787_CLASS_TYPE.mkd' PAGESIZE=4096 (
 "CLASS_ID" CHAR(4),
 "TYPE_ID" CHAR(5),
 "PREFIX_CHAR" CHAR(4),
 "DESC_TEMPLATE" CHAR(50),
 "INV_UM" CHAR(2),
 "PURCH_UM" CHAR(2),
 "PACKAGING" CHAR(15),
 "ABC" CHAR(1),
 "RUNSCRAP" DOUBLE,
 "SETUP_QTY" NUMERIC(8,0),
 "ORDER_QTY" NUMERIC(8,0),
 "SAFETY_STOCK" NUMERIC(8,0),
 "REORDERPOINT" NUMERIC(8,0),
 "BUYER" CHAR(6),
 "LEAD_DAYS" NUMERIC(8,0),
 "AMT_COST" DOUBLE,
 "INSPECTION_REQ" BIT NOT NULL,
 "CERTIFICATE_REQ" BIT NOT NULL,
 "MRC" CHAR(10),
 "NCNR" CHAR(50),
 "CERTIFICATION" CHAR(20),
 "SENSITIVE" CHAR(20),
 "DOCUMENTATION" CHAR(30) );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
